repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        args:
          - --safe
          - --target-version=py36

  - repo: git://github.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8

  - repo: git://github.com/pre-commit/mirrors-isort
    rev: v4.3.18
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        verbose: true

  - repo: git://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
    -   id: mypy
        verbose: true
        files: kartothek
