language: python

# needed for python>=3.7
dist: xenial

python:
  - 3.6
  - 3.7

env:
  - KARTOTHEK_ARROW_VERSION=0.12.1
  - KARTOTHEK_ARROW_VERSION=0.13.0

before_install:
  - pip install --upgrade pip-tools
  - ./compile_requirements.sh
  - python setup.py bdist_wheel

install:
  - pip install --upgrade -r test-requirements-pinned.txt
  - pip install --upgrade pytest
  - pip install --no-deps dist/*

before_script:
  - pip freeze
  - ci/check_format.sh

script:
  - pytest

matrix:
  allow_failures:
  - python: 3.7