language: python

# needed for python>=3.7
dist: xenial

python:
  - 3.6
  - 3.7

env:
  - KARTOTHEK_ARROW_VERSION=0.12.1
  - KARTOTHEK_ARROW_VERSION=0.13.0

before_install:
  - pip install --upgrade pip
  - pip install pip-tools
  - ./compile_requirements.sh
  - python setup.py bdist_wheel

install:
  - pip install -r test-requirements-pinned.txt
  - pip install --no-deps dist/*

# If docs break or formatting, linting is off, I'd like to know immediately
before_script:
  - pip freeze
  - pip install pre-commit && pre-commit run -a
  - python setup.py docs

script:
  - pytest

after_success:
  - pip install codecov
  - codecov

deploy:
  provider: pypi
  user: fjetter
  server: https://test.pypi.org/legacy
  password:
    secure: jIhp3YW3E/Ri2X2Bl+5wAl5mLptZNN8dTCuegKpbVCOL7tWSK/5HTrQrUIGxllFtLGglYjN7KqmFS5SAws/HcqLzEYr3FAe07NCMF44GRxQZBjm+rnh4YVh1q3giwmyfqWvpD/KRi90r5kDt5hBYJJiYGvhYWxKBh5yXFaAx4hCgzzhCnbE3ZLWsNmVtIvubDq6126/BbhH8+GsnbmUvay/BVIIZQ+QTqfartvE5ibGrbPOrMMEgmfW63x6B5eZsOoaj4Nu8zI+m+D0VxaDXxO5lUfBSQ8Lwa3nhXhrhf19qlkMrYNW0vHSCiDx9WBzLGWDpJVCl5AUneebLvynPdUWca+GFfqdD9MdxRKrjJZnJZfq8PrCG3cjeTR+3VOb7fOApnvXeblocXuK9yJmTOnv3Gx9r95953W1/WwTOpOCKdEfokmxu6Cv0Jy5oX3tHripED3ihTLHfjGV1DWqeXGohJCr4qkTC2DTU84rFkJqUalQ9Kh2F7qip1J0M/oV/s1IJUKUHsccVcNp/ck8YlAazZZZqPWJwXtrMaR6PsA/b7o9sfd7V4JTxK1miyD1e2EZsUkbdl6gOo8Dx0ZzjwwUSvd3bCywNw1G2yH2fkISyE2YU8AEEnyGmx2RA6lUVGfWu0R2NxnYU1lMQwEa3Y6nCCRYoXg+zuGVtVDikkTk=
  distributions: sdist bdist_wheel
  on:
    branch: test_release
  skip_existing: true
